name: GHPages-Doxygen Action

on:
  push:
    branches: [ main ]

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout with submodules
      uses: actions/checkout@v3
      with:
       submodules: recursive
    
    - name: Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.4
      with:
        working-directory: "./docs"
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
